# Generated by Django 5.2.4 on 2025-09-05 08:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_groups_user_is_staff_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='farm_name',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('DISTRIBUTOR', 'Distributor'), ('DELIVERY_BOY', 'Delivery Boy')], default='CUSTOMER', max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryBoyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_info', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='DistributorInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farm_name', models.CharField(blank=True, max_length=100, null=True)),
                ('distributor_code', models.CharField(db_index=True, max_length=10, unique=True)),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_info', to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDistributorLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distributor_links', to=settings.AUTH_USER_MODEL)),
                ('distributor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_links', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('customer', 'distributor')},
            },
        ),
    ]
