# Generated by Django 5.2.4 on 2025-09-09 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_profile_farm_name_user_role_deliveryboyinfo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='role',
            field=models.CharField(choices=[('CUSTOMER', 'Customer'), ('DISTRIBUTOR', 'Distributor'), ('DELIVERY_BOY', 'Delivery Boy')], default='CUSTOMER', max_length=20),
        ),
    ]
